name: Label & Comment Issues

 

on:
  issues:
    types: [opened, reopened, closed]

 

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.issue.state == 'open'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.

 

  close_issue:
    needs: label_issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.issue.state == 'closed' && github.event.issue.pull_request == null
    steps:
      - name: Comment on closed issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: The issue is now resolved.
